# Starter pipeline
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'AWS_for_TF_Gfi_RSP'
    backendAWSBucketName: 'cloudfabric-terraform-state'
    backendAWSKey: 'rsp'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'AWS_for_TF_Gfi_RSP'

- task: TerraformTaskV1@0
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'AWS_for_TF_Gfi_RSP'